---
# Source: kube-prometheus-stack/templates/alertmanager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-kube-prom-alertmanager
  namespace: monitoring-system
  labels:
    app: kube-prometheus-stack-alertmanager
    self-monitor: "true"
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/version: "16.0.1"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-16.0.1
    release: "prometheus-stack"
    heritage: "Helm"
spec:
  ports:
  - name: web
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: alertmanager
    alertmanager: prometheus-stack-kube-prom-alertmanager
  type: "ClusterIP"
