
resources:
- ../templated/7.10.1/elasticsearch/templates/poddisruptionbudget.yaml
- ../templated/7.10.1/elasticsearch/templates/service.yaml
- ../templated/7.10.1/elasticsearch/templates/statefulset.yaml
