apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: managed-nfs-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
