apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-dev
resources:
#- ./api-specifications
- ./namespace.yaml
bases:
- ../../base/secrets
- ../../base/networking/np-acme-certmanager.yaml
- ../../base/networking/np-allow-all-namespace-internal.yaml
- ../../base/networking/np-allow-traefik-ingress.yaml
