# helm repo add jetstack https://charts.jetstack.io
# helm repo update
# helm search repo jetstack/cert-manager --versions
# helm pull jetstack/cert-manager --version v1.1.0 --untar --untardir ./helm/1.1.0/
# Adjust the ./helm-certmanager-values.yaml
# helm template --name-template=cert-manager-central --namespace none  --values helm-certmanager-values.yaml --output-dir ./templated/1.1.0 ./helm/1.1.0/cert-manager/ 


# Ref.: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
# Ref.: https://helm.sh/docs/chart_best_practices/

resources:
- templated/1.1.0/cert-manager/templates/cainjector-deployment.yaml
- templated/1.1.0/cert-manager/templates/cainjector-rbac.yaml
- templated/1.1.0/cert-manager/templates/cainjector-serviceaccount.yaml
- templated/1.1.0/cert-manager/templates/deployment.yaml
- templated/1.1.0/cert-manager/templates/rbac.yaml
- templated/1.1.0/cert-manager/templates/service.yaml
- templated/1.1.0/cert-manager/templates/serviceaccount.yaml
- templated/1.1.0/cert-manager/templates/webhook-deployment.yaml
- templated/1.1.0/cert-manager/templates/webhook-mutating-webhook.yaml
- templated/1.1.0/cert-manager/templates/webhook-rbac.yaml
- templated/1.1.0/cert-manager/templates/webhook-service.yaml
- templated/1.1.0/cert-manager/templates/webhook-serviceaccount.yaml
- templated/1.1.0/cert-manager/templates/webhook-validating-webhook.yaml


#patches:
#- target:
#    kind: Deployment
#  path: ../../base/patch-image-pull-secret.json
