apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./np-acme-certmanager.yaml
- ./np-allow-all-namespace-internal.yaml
- ./np-allow-dhc-toolbox-ingress.yaml
- ./np-allow-incoming-traefik-for-dashboard-proxy.yaml
- ./np-allow-traefik-ingress.yaml

