# helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
# helm repo update
# helm search repo sealed-secrets/sealed-secrets --versions
# helm pull sealed-secrets/sealed-secrets --version 1.13.2 --untar --untardir ./helm/0.13.1/
# Adjust the ./helm-sealedsecrets-values.yaml
# helm template --name-template=sealed-secrets-controller-central --namespace none  --values helm-sealedsecrets-values.yaml --output-dir ./templated/1.1.0 ./helm/0.13.1/sealed-secrets/ 


# Ref.: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
# Ref.: https://helm.sh/docs/chart_best_practices/

resources:
- templated/1.1.0/sealed-secrets/templates/cluster-role-binding.yaml
- templated/1.1.0/sealed-secrets/templates/cluster-role.yaml
- templated/1.1.0/sealed-secrets/templates/deployment.yaml
- templated/1.1.0/sealed-secrets/templates/role-binding.yaml
- templated/1.1.0/sealed-secrets/templates/role.yaml
- templated/1.1.0/sealed-secrets/templates/sealedsecret-crd.yaml
- templated/1.1.0/sealed-secrets/templates/service-account.yaml
- templated/1.1.0/sealed-secrets/templates/service.yaml

#patches:
#- target:
#    kind: Deployment
#  path: ../../base/patch-image-pull-secret.json
