# Default values for jaeger-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: jaegertracing/jaeger-operator
  tag: 1.22.1
  pullPolicy: Always
  imagePullSecrets: []

crd:
  install: true

jaeger:
  # Specifies whether Jaeger instance should be created
  create: true
  # namespace where Jaeger resource should be created default to .Release.Namespace
  namespace:
  spec: {}

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: true
  clusterRole: true
