# helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
# helm repo update
# helm search repo jaegertracing/jaeger-operator --versions
# WARNING: APP VERSION of jaegertracing/jaeger and jaegertracing/jaeger-operator do require to have the same major and minor version if used as separat Helm chart. E.g. 1.22.x. 
# helm pull jaegertracing/jaeger-operator --version 2.21.4 --untar --untardir ./helm/1.22.1/
# Adjust the ./jaeger-operator-values.yaml
# helm template --name-template=jaeger-stack --namespace none  --values ./jaeger-operator-values.yaml --output-dir ./templated/1.22.1 ./helm/1.22.1/jaeger-operator/

# Ref.: https://github.com/jaegertracing/jaeger
# Ref.: https://github.com/jaegertracing/jaeger-operator
# Ref.: https://github.com/jaegertracing/jaeger-operator#jaeger-operator-vs-jaeger
# Ref.: https://github.com/jaegertracing/helm-charts

resources:
## Custom Resource Definitions
## WARNING: Have to be copied manually from helm folder
- templated/1.22.1/jaeger-operator/templates/crds/crd.yaml

## Application templates
- templated/1.22.1/jaeger-operator/templates/deployment.yaml
- templated/1.22.1/jaeger-operator/templates/jaeger.yaml
- templated/1.22.1/jaeger-operator/templates/psp.yaml
- templated/1.22.1/jaeger-operator/templates/role-binding.yaml
- templated/1.22.1/jaeger-operator/templates/role.yaml
- templated/1.22.1/jaeger-operator/templates/service-account.yaml
- templated/1.22.1/jaeger-operator/templates/service.yaml


#patches:
#- target:
#    kind: Deployment
#  path: ../../base/patch-image-pull-secret.json
