version: 1 # must be `1`
kind: Kustomization
patchUpdated:
  generators:
  - command: kustomize build . --load_restrictor none
  patchFile: flux-patch.yaml ##required for auto container image updates to latest
  
#  updaters:
#  - containerImage:
#    command: kustomize edit set image $FLUX_CONTAINER=$FLUX_IMG:$FLUX_TAG

## references:
## .flux.yaml: https://github.com/fluxcd/flux/blob/v1.20.0/docs/references/fluxyaml-config-files.md
## --load_restrictor: https://kubernetes-sigs.github.io/kustomize/faq/
