---
# Source: kube-prometheus-stack/charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-prometheus-stack-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: prometheus-stack
    chart: prometheus-node-exporter-1.18.0
    jobLabel: node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-stack-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-stack-prometheus-node-exporter
    namespace: monitoring-system
