IMAGE_NAME = "bento/ubuntu-20.04"
IMAGE_VERSION = "202010.24.0"
N = 1


Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
	config.vm.synced_folder ".", "/vagrant"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048 # minum is 2048mb
        v.cpus = 2 # minum is 2
		v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"] # required for windows
    end
	
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
		master.vm.box_version = IMAGE_VERSION
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible_local" do |ansible|
		
			ansible.install_mode = "pip"
#			ansible.version = "2.7.13"
#			ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
			
            ansible.playbook = "ansible-plays/k8s-master-playbook.yaml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "k8s-worker-#{i}" do |node|
			node.vm.box = IMAGE_NAME
			node.vm.box_version = IMAGE_VERSION
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "k8s-worker-#{i}"
            node.vm.provision "ansible_local" do |ansible|
				ansible.install_mode = "pip"
				#ansible.version = "2.7.13"
				#ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
			
                ansible.playbook = "ansible-plays/k8s-worker-playbook.yaml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end
end	