---
# Source: logstash/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: central-logstash-config
  labels:
    app: "central-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "central"
data:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
