---
# Source: logstash/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "central-logstash-pdb"
  labels:
    app: "central-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "central"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "central-logstash"
