---
# Source: logstash/templates/service-headless.yaml
kind: Service
apiVersion: v1
metadata:
  name: "central-logstash-headless"
  labels:
    app: "central-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "central"
spec:
  clusterIP: None
  selector:
    app: "central-logstash"
  ports:
    - name: http
      port: 9600
