---
# Source: sealed-secrets/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-controller-central-key-admin
  namespace: none
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.13.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/version: 0.13.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-controller-central-key-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: sealed-secrets-controller-central
    namespace: none
---
# Source: sealed-secrets/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-controller-central-service-proxier
  namespace: none
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.13.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/version: 0.13.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-controller-central-service-proxier
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
