---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-controller-central-key-admin
  namespace: none
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.13.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/version: 0.13.1
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-key
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-controller-central-service-proxier
  namespace: none
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.13.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/version: 0.13.1
rules:
- apiGroups:
  - ""
  resourceNames:
  - 'http:sealed-secrets-controller-central:'
  - sealed-secrets-controller-central
  resources:
  - services/proxy
  verbs:
  - create
  - get
