---
# Source: sealed-secrets/templates/sealedsecret-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
  
  annotations:
    "helm.sh/resource-policy": keep
  
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.13.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/version: 0.13.1
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
