# helm fetch --repo https://edcs3chartsb.s3-edc.emea.svc.corpintra.net/repo --untar --untardir ./helm/1.86.1 traefik
# helm template -n traefik --values kubernetes_values.yaml --output-dir ./templated/1.86.1 helm/1.86.1/traefik/
resources:
- templated/1.86.1/traefik/templates/configmap.yaml
- templated/1.86.1/traefik/templates/dashboard-ingress.yaml
- templated/1.86.1/traefik/templates/dashboard-service.yaml
- templated/1.86.1/traefik/templates/deployment.yaml
- templated/1.86.1/traefik/templates/networkpolicy.yaml
- templated/1.86.1/traefik/templates/rbac.yaml
- templated/1.86.1/traefik/templates/service.yaml
- templated/1.86.1/traefik/templates/default-cert-secret.yaml
patches:
- target:
    kind: Deployment
  path: ../../base/patch-image-pull-secret.json
