---
# Source: metricbeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat-central-metricbeat-cluster-role-binding
  labels:
    app: "metricbeat-central-metricbeat"
    chart: "metricbeat-7.10.1"
    heritage: "Helm"
    release: "metricbeat-central"
roleRef:
  kind: ClusterRole
  name: metricbeat-central-metricbeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: metricbeat-central-metricbeat
  namespace: none
