---
# Source: metricbeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat-central-metricbeat
  annotations:
  labels:
    app: "metricbeat-central-metricbeat"
    chart: "metricbeat-7.10.1"
    heritage: "Helm"
    release: "metricbeat-central"
