---
# Source: jaeger-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jaeger-stack-jaeger-operator-metrics
  namespace: none
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger-stack
spec:
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger-stack
  type: ClusterIP
