apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources
    namespace: admin
  spec:
    hard:
      requests.memory: 1.5Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: default-limit-range
    namespace: admin
  spec:
    limits:
    - default:
        memory: 500Mi
        cpu: 1000m
      defaultRequest:
        memory: 100Mi
        cpu: 100m
      max:
        cpu: 4000m
        memory: 5000Mi
      type: Container