---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-central-filebeat-cluster-role-binding
  labels:
    app: "filebeat-central-filebeat"
    chart: "filebeat-7.10.1"
    heritage: "Helm"
    release: "filebeat-central"
roleRef:
  kind: ClusterRole
  name: filebeat-central-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-central-filebeat
  namespace: none
