---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: central-filebeat-cluster-role-binding
  labels:
    app: "central-filebeat"
    chart: "filebeat-7.10.1"
    heritage: "Helm"
    release: "central"
roleRef:
  kind: ClusterRole
  name: central-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: central-filebeat
  namespace: none
