---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: central-filebeat-cluster-role
  labels:
    app: "central-filebeat"
    chart: "filebeat-7.10.1"
    heritage: "Helm"
    release: "central"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
