---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-central-filebeat
  annotations:
  labels:
    app: "filebeat-central-filebeat"
    chart: "filebeat-7.10.1"
    heritage: "Helm"
    release: "filebeat-central"
