apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system
resources:
- ./namespace.yaml
- ./elastic-stack
- ./grafana
- ./jaeger
- ./kubernetes-dashboard
- ./kube-state-metrics
- ./prometheus-stack


bases:
- ../../base/secrets
- ../../base/networking/np-acme-certmanager.yaml
- ../../base/networking/np-allow-all-namespace-internal.yaml
- ../../base/networking/np-allow-traefik-ingress.yaml
