---
# Source: apm-server/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apm-server-central-apm-server-cluster-role-binding
  labels:
    app: "apm-server-central-apm-server"
    chart: "apm-server-7.10.1"
    heritage: "Helm"
    release: "apm-server-central"
roleRef:
  kind: ClusterRole
  name: apm-server-central-apm-server-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: apm-server-central-apm-server
  namespace: none
