---
# Source: apm-server/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: central-apm-server-cluster-role
  labels:
    app: "central-apm-server"
    chart: "apm-server-7.10.1"
    heritage: "Helm"
    release: "central"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
