---
# Source: apm-server/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-central-apm-server-config
  labels:
    app: "apm-server-central-apm-server"
    chart: "apm-server-7.10.1"
    heritage: "Helm"
    release: "apm-server-central"
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    
    queue: {}
    
    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      ## If you have security enabled- you'll need to add the credentials
      ## as environment variables
      # username: "${ELASTICSEARCH_USERNAME}"
      # password: "${ELASTICSEARCH_PASSWORD}"
      ## If SSL is enabled
      # protocol: https
      # ssl.certificate_authorities:
      #  - /usr/share/apm-server/config/certs/elastic-ca.pem
