---
# Source: apm-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-apm-server
  labels:
    app: apm-server
    release: "central"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: apm-server
      release: "central"
  template:
    metadata:
      labels:
        app: apm-server
        release: "central"
      annotations:
        
        configChecksum: 8870102f8174b3345b7d711a1a45fcc86ea51064f3635234d89f5c4ea1a67ca
    spec:
      serviceAccountName: central-apm-server
      volumes:
        - name: apm-server-config
          configMap:
            name: central-apm-server-config
            defaultMode: 0600
      containers:
      - name: apm-server
        image: "docker.elastic.co/apm/apm-server-oss:7.10.1"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: false
          runAsUser: 0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
          - containerPort: 8200
            name: http
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: apm-server-config
            mountPath: /usr/share/apm-server/apm-server.yml
            subPath: apm-server.yml
            readOnly: true
