---
# Source: apm-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apm-server-central-apm-server
  annotations:
  labels:
    app: "apm-server-central-apm-server"
    chart: "apm-server-7.10.1"
    heritage: "Helm"
    release: "apm-server-central"
